version: '3.9'

services:
  nginx:
    build: .
    ports:
      - 8080:80

  node:
    build: ./node
    command: npm start
    ports:
      - 3000:3000
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=imse-database
      - MONGODB_CONNSTRING=mongodb://mongoadmin:secret@mongodb

  mysql:
    image: mysql:8-oracle
    volumes:
      - imse-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: imse-database

  mongodb:
    image: mongo:5.0.8
    volumes:
      - imse-mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret

volumes:
  imse-mysql-data:
  imse-mongodb-data: