version: "3.9"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/ssl/private
    ports:
      - 8080:80

  angular:
    build: ./angular
    command: npm start
    working_dir: /app
    volumes:
      - ./angular:/app
    ports:
      - 4200:4200
      - 49153:49153

  node:
    build: ./node
    command: npm run dev
    ports:
      - 3000:3000
      - 9229:9229
    working_dir: /app
    volumes:
      - ./node/target:/app/target
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=imse-database
      - MONGODB_CONNSTRING=mongodb://mongoadmin:secret@mongodb

  mysql:
    image: mysql:8-oracle
    ports:
      - 3306:3306
    volumes:
      - imse-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: imse-database

  mongodb:
    image: mongo:5.0.8
    ports:
      - 27017:27017
    volumes:
      - imse-mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret


volumes:
  imse-mysql-data:
  imse-mongodb-data: